### ISSUE TITLE
This package is just a cheap copy of an original package and violates MIT License

### ISSUE THREAD

**Issue by deligoez** [bvtterfly/laravel-hashids#2]
**This package is just a cheap copy of an original package and violates MIT License.**

The original package is located just here:
https://github.com/deligoez/laravel-model-hashid

I'm just leaving a small note here because I don't even see it worth creating a new DMCA Takedown notice

**Comment by bvtterfly** [comment]
I need to use Hashids in one of my projects, so I created a module in that project inspired by Spatie's [Laravel Sluggable](https://github.com/spatie/laravel-sluggable) package.
Now I export it as a package and publish it.
It's just a straightforward package, So I don't even search to find a Laravel package for it. If I knew your package existed, I would use it. 
Relax, It's not a copy. We develop a laravel package for the same `hashids/hashids` package.

**Comment by deligoez** [comment]
I was completely wrong here and I apologize publicly to you and your package.

Since it is not possible to delete the issue, I will clear the title and its content to avoid misunderstandings in the use of your package.
